apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: liveblog-s3
  annotations:
    volume.alpha.kubernetes.io/storage-class: any
  labels:
    app: liveblog
  namespace: liveblog
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 10Gi
